#!/usr/bin/env bash


#-----------------------------------------------------------------------------------------------------------------------
#
# Git Delete Branches Subcommand
#
# Description:
#
#   This file defines a delete branches subcommand (summarize).
#
#   This subcommand deletes both the local and remote copies of the specified branches. If a branch does not exist on
#   the local or the remote it is ignored (i.e. it does not cause a failure).
#
#-----------------------------------------------------------------------------------------------------------------------


# When executing a pipeline of commands, the pipeline's exit code will be the exit code from the rightmost command to
# exit with a non-zero exit status or 0 if all command succeed. Normally, the code comes from the final command.
set -o pipefail

# Treat any undefined variables that are referenced in substitutions as an error.
set -u


function main
{
    # Verify that the correct number of command arguments was specified.
    if [[ ${#} -lt 1 ]]; then
        echo "Error: Too few command line arguments specified"
        echo "Usage: git delete-branches <branch> [branch ...]"
        return 1
    fi &&

    local branches=("${@}")

    # Delete the local and remote copy of each branch.
    for branch in "${branches[@]}"
    do
        git branch -D "${branch}"
        git push origin ":${branch}"
    done
}


main "${@}"
